spring:
  application:
    name: order-service
    rabbitmq:
    host: 192.168.175.133
    port: 15672
    username: admin
    password: admin
server:
  port: 8201  
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  cloud:
    config:
      override-none: true
      
feign:
  hystrix:
    enabled: true
item-service:
  ribbon:
    
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream